// Practice mode smoke test: local host, human mech, two bot tops. Needs `npm run dev`.
import { chromium } from 'playwright';
const BASE = process.env.BASE_URL ?? 'http://localhost:5211/';
const OUT = process.env.SHOT_DIR ?? 'e2e/out';
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
await page.goto(BASE);
await page.waitForFunction(() => window.spinArena);
await page.click('#practice');
await page.click('#start');
const state = () => page.evaluate(() => { const s = window.spinArena.session, a = s.arena; return { phase: s.lobby.phase, clock: a?.clock ?? null, shadows: a?.shadows.length ?? 0, health: a?.mech.status.health, x: a?.mech.x, z: a?.mech.z }; });
await page.waitForTimeout(3500);
const s0 = await state();
await page.keyboard.down('KeyD');
await page.waitForTimeout(800);
await page.keyboard.up('KeyD');
const s1 = await state();
await page.waitForTimeout(9000);
const s2 = await state();
await page.screenshot({ path: `${OUT}/practice.png` });
let ok = true;
const check = (name, cond) => { console.log(`${cond ? 'PASS' : 'FAIL'} ${name}`); ok &&= cond; };
check('round is playing', s0.phase === 'playing' || s2.phase === 'over');
check('clock advances', s2.clock > s0.clock + 5);
check('D key moves the mech toward +X', s1.x > s0.x + 1);
check('bot dashes create shadows', s2.shadows > 0);
check('no page errors', errors.length === 0);
if (errors.length) console.log(errors.join('\n'));
console.log(JSON.stringify({ s0, s1, s2 }));
await browser.close();
process.exit(ok ? 0 : 1);
